package com.oncall.toolgateway;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.sql.Types;

/**
 * 基于 JDBC 的工具审计 —— <b>生产必须用这个</b>。
 *
 * <p>只用 JDK 自带的 {@code javax.sql} / {@code java.sql}，
 * 因此 {@code oncall-tool-gateway} 的生产代码仍然不引入 ORM 或连接池
 * （H2 只在测试作用域），与 {@link JdbcToolExecutionLedger} 一致。
 *
 * <p><b>不用方言语法</b>：纯 {@code INSERT}，H2 与 PostgreSQL 都成立。
 *
 * <h2>这个类为什么直到这一轮才写出来</h2>
 *
 * 不是因为没写，是因为<b>写不出来</b>。{@code tool_audit_log} 有 7 个
 * {@code NOT NULL} 列，而原先 {@code ToolAuditLog} 的方法签名一个都给不出——
 * 尤其 {@code trace_id}：整个生产代码里 {@code traceId} 零命中，
 * 没有任何东西能产出它。硬写只能往必填列塞假值，
 * 而<b>一张字段造假的审计表比没有审计更糟</b>。
 * 现在上下文由 {@link ToolAuditContext} 显式传入、事件由 {@link ToolAuditEvent}
 * 在构造期校验，这个类才第一次有合法的数据可写。
 *
 * <p><b>顺带一个发现</b>：旧签名每个方法的第一个参数都是 {@code idempotencyKey}，
 * 而 {@code tool_audit_log} <b>根本没有这一列</b>——
 * 旧接口唯一传得出来的东西，恰好是表里放不下的那个。
 */
public final class JdbcToolAuditLog implements ToolAuditLog {

    /**
     * 建表 DDL（跨方言）。生产环境由 Flyway 管理，见
     * {@code db/migration/V2__agent_execution.sql}。
     */
    public static final String CREATE_TABLE_SQL = """
            CREATE TABLE IF NOT EXISTS %s (
                id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                trace_id       VARCHAR(64)  NOT NULL,
                run_id         VARCHAR(64),
                step_id        VARCHAR(64),
                tool_name      VARCHAR(191) NOT NULL,
                tool_source    VARCHAR(32)  NOT NULL,
                risk_level     VARCHAR(32)  NOT NULL,
                args_masked    TEXT         NOT NULL,
                result_masked  TEXT,
                gate_outcome   VARCHAR(32)  NOT NULL,
                denied_reason  VARCHAR(500),
                operator       VARCHAR(64),
                duration_ms    INT,
                called_at      TIMESTAMP    NOT NULL
            )
            """;

    private static final String COLUMNS =
            "(trace_id, run_id, step_id, tool_name, tool_source, risk_level,"
                    + " args_masked, result_masked, gate_outcome, denied_reason,"
                    + " operator, duration_ms, called_at)";

    private final DataSource dataSource;
    private final String table;

    public JdbcToolAuditLog(DataSource dataSource) {
        this(dataSource, "tool_audit_log");
    }

    public JdbcToolAuditLog(DataSource dataSource, String table) {
        if (dataSource == null) {
            throw new IllegalArgumentException("dataSource 不能为 null");
        }
        this.dataSource = dataSource;
        this.table = table;
    }

    /** 建表（幂等）。测试与首次启动用；生产建议交给 Flyway。 */
    public void createSchemaIfMissing() {
        try (Connection c = dataSource.getConnection(); Statement st = c.createStatement()) {
            st.execute(String.format(CREATE_TABLE_SQL, table));
        } catch (SQLException e) {
            throw new IllegalStateException("建表失败：" + table, e);
        }
    }

    @Override
    public void record(ToolAuditEvent event) {
        if (event == null) {
            throw new IllegalArgumentException("event 不能为 null");
        }
        // 事件在构造期已经校验过必填项，这里不再重复判断——
        // 重复校验会让「到底哪一层负责保证」变得模糊。
        String sql = "INSERT INTO " + table + " " + COLUMNS + " VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)";
        try (Connection c = dataSource.getConnection(); PreparedStatement ps = c.prepareStatement(sql)) {
            ToolAuditContext ctx = event.context();
            ps.setString(1, ctx.traceId());
            setNullable(ps, 2, ctx.runId());
            setNullable(ps, 3, ctx.stepId());
            ps.setString(4, event.toolName());
            ps.setString(5, event.toolSource().name());
            ps.setString(6, event.riskLevel().name());
            ps.setString(7, event.argsMasked());
            setNullable(ps, 8, event.resultMasked());
            ps.setString(9, event.gateOutcome().name());
            setNullable(ps, 10, event.deniedReason());
            setNullable(ps, 11, ctx.operator());
            if (event.durationMs() == null) {
                ps.setNull(12, Types.INTEGER);
            } else {
                ps.setInt(12, event.durationMs());
            }
            ps.setTimestamp(13, Timestamp.from(event.calledAt()));
            ps.executeUpdate();
        } catch (SQLException e) {
            // 必须抛出去，不能吞。
            // 审计写不进去而调用方毫不知情，等于「有审计」这个前提是假的——
            // 而排查时第一个被信任的就是审计表。
            throw new IllegalStateException("写入工具审计失败：" + event.toolName()
                    + " trace=" + event.context().traceId(), e);
        }
    }

    /** 行数，供自检与保留期清理任务使用。 */
    public int count() {
        try (Connection c = dataSource.getConnection();
             Statement st = c.createStatement();
             ResultSet rs = st.executeQuery("SELECT COUNT(*) FROM " + table)) {
            return rs.next() ? rs.getInt(1) : 0;
        } catch (SQLException e) {
            throw new IllegalStateException("统计审计行数失败", e);
        }
    }

    /**
     * 按链路取审计流水，按时间升序。
     *
     * <p>这是审计表最主要的查询（DDL 为此建了 {@code idx_tool_audit_trace}）：
     * 「这次排查都调了哪些工具、哪道关卡拦过」。
     */
    public java.util.List<ToolAuditEvent> byTrace(String traceId) {
        if (traceId == null || traceId.isBlank()) {
            throw new IllegalArgumentException("traceId 不能为空");
        }
        String sql = "SELECT trace_id, run_id, step_id, tool_name, tool_source, risk_level,"
                + " args_masked, result_masked, gate_outcome, denied_reason,"
                + " operator, duration_ms, called_at FROM " + table
                + " WHERE trace_id=? ORDER BY called_at, id";
        try (Connection c = dataSource.getConnection(); PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setString(1, traceId);
            try (ResultSet rs = ps.executeQuery()) {
                java.util.List<ToolAuditEvent> out = new java.util.ArrayList<>();
                while (rs.next()) {
                    out.add(new ToolAuditEvent(
                            new ToolAuditContext(rs.getString(1), rs.getString(2),
                                    rs.getString(3), rs.getString(11)),
                            rs.getString(4),
                            com.oncall.domain.tool.ToolSource.valueOf(rs.getString(5)),
                            com.oncall.domain.tool.RiskLevel.valueOf(rs.getString(6)),
                            rs.getString(7),
                            rs.getString(8),
                            GateOutcome.valueOf(rs.getString(9)),
                            rs.getString(10),
                            rs.getInt(12) == 0 && rs.wasNull() ? null : rs.getInt(12),
                            rs.getTimestamp(13).toInstant()));
                }
                return out;
            }
        } catch (SQLException e) {
            throw new IllegalStateException("查询审计流水失败：trace=" + traceId, e);
        }
    }

    /**
     * {@code setString(idx, null)} 在部分驱动上会按 VARCHAR 处理并报错，
     * 所以可空列一律走 {@code setNull} 并显式给出类型。
     */
    private static void setNullable(PreparedStatement ps, int idx, String value) throws SQLException {
        if (value == null) {
            ps.setNull(idx, Types.VARCHAR);
        } else {
            ps.setString(idx, value);
        }
    }
}
