-- =====================================================================
-- 配置治理表（对应模块 oncall-config）
--
-- 设计说明见《配置外置与前端可配置设计.md》。两条关键约束：
--
-- 1. app_config 只存「被改过」的键。默认值留在代码的 ConfigSpec 声明里，
--    这样「哪些参数被改离了基线」一条 SQL 就能查出来。
--
-- 2. 恢复默认时不 DELETE，而是把 config_value 置 NULL 留墓碑行。
--    因为 JdbcConfigStore.revision() 取 MAX(revision)，真删行会让修订号倒退，
--    导致 ConfigService 的快照缓存误判为「没变化」而读到旧值。
--    墓碑行数量上限 = 配置项总数，不会无限增长。
--
-- 方言：PostgreSQL 10+。H2 2.x 亦可执行（测试用），
--       但 H2 侧建表由 JdbcConfigStore.createSchemaIfMissing() 负责。
-- =====================================================================

CREATE TABLE IF NOT EXISTS app_config (
    config_key    VARCHAR(191)   NOT NULL PRIMARY KEY,
    -- NULL 表示「已恢复默认」的墓碑行，见上方说明
    config_value  VARCHAR(2000),
    revision      BIGINT         NOT NULL,
    updated_at    TIMESTAMP      NOT NULL,
    updated_by    VARCHAR(64)
);

COMMENT ON TABLE  app_config               IS '配置覆盖值；默认值在代码 ConfigSpec 声明里';
COMMENT ON COLUMN app_config.config_value  IS 'NULL = 墓碑行（已恢复默认），保留以维持 revision 单调';
COMMENT ON COLUMN app_config.revision      IS '单调递增，供 ConfigService 快照缓存失效判断';

-- 部分索引：只索引真正生效的行，跳过墓碑
CREATE INDEX IF NOT EXISTS idx_app_config_live
    ON app_config (config_key)
    WHERE config_value IS NOT NULL;


CREATE TABLE IF NOT EXISTS config_audit_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key    VARCHAR(191)   NOT NULL,
    old_value     VARCHAR(2000),
    -- NULL 表示「恢复默认」而不是「设置为某个值」
    new_value     VARCHAR(2000),
    operator      VARCHAR(64)    NOT NULL,
    reason        VARCHAR(500),
    tier          VARCHAR(32)    NOT NULL,
    changed_at    TIMESTAMP      NOT NULL
);

COMMENT ON TABLE  config_audit_log           IS '配置变更审计；保留期与 tool_audit_log 同级（建议 180 天）';
COMMENT ON COLUMN config_audit_log.new_value IS 'NULL = 这次变更是恢复默认值';
COMMENT ON COLUMN config_audit_log.tier      IS 'ConfigTier：RUNTIME_HOT / REQUIRES_MIGRATION / BACKEND_ONLY';

CREATE INDEX IF NOT EXISTS idx_config_audit_key ON config_audit_log (config_key, changed_at);
CREATE INDEX IF NOT EXISTS idx_config_audit_time ON config_audit_log (changed_at DESC);
