-- =====================================================================
-- Agent 执行链（对应模块 oncall-agent / oncall-tool-gateway）
--
-- 设计说明见《5.数据库设计文档.md》第三节。三条关键约束：
--
-- 1. agent_run.step_cursor 让排查循环可断点续跑。worker 崩溃后从 cursor
--    继续，不从头重来，也不会重复执行已完成的步骤。
--
-- 2. agent_run.autonomy_level 存的是「当时的」放权等级快照，不是引用。
--    放权等级会变，但「当时是在什么授权下做的」必须固定下来。
--
-- 3. agent_step.idempotency_key 的 UNIQUE 约束是幂等的物理保证。
--    应用层的 IdempotencyStore 在多实例下会失效——两个 worker 同时拿到
--    同一个重投消息，各自查内存都说「没执行过」。数据库约束是唯一兜底。
--
-- 方言：PostgreSQL 10+
-- =====================================================================

CREATE TABLE IF NOT EXISTS agent_run (
    id               VARCHAR(64)    NOT NULL PRIMARY KEY,
    trace_id         VARCHAR(64)    NOT NULL,
    alert_group_id   VARCHAR(64),
    status           VARCHAR(32)    NOT NULL,
    autonomy_level   VARCHAR(32)    NOT NULL,
    step_cursor      INT            NOT NULL DEFAULT 0,
    budget_steps     INT            NOT NULL,
    budget_tokens    BIGINT         NOT NULL,
    budget_cost      NUMERIC(12,6)  NOT NULL,
    used_steps       INT            NOT NULL DEFAULT 0,
    used_tokens      BIGINT         NOT NULL DEFAULT 0,
    used_cost        NUMERIC(12,6)  NOT NULL DEFAULT 0,
    created_at       TIMESTAMP      NOT NULL,
    finished_at      TIMESTAMP
);

COMMENT ON TABLE  agent_run                 IS '一次排查的全过程；预算三重护栏（步数/token/成本）';
COMMENT ON COLUMN agent_run.step_cursor     IS '断点续跑位置；worker 崩溃后从此处继续';
COMMENT ON COLUMN agent_run.autonomy_level  IS '放权等级快照，不是引用——授权条件必须固定';
COMMENT ON COLUMN agent_run.status          IS 'RUNNING / SUCCEEDED / FAILED / ABORTED / HANDED_OVER';

CREATE INDEX IF NOT EXISTS idx_agent_run_status ON agent_run (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_run_trace  ON agent_run (trace_id);


CREATE TABLE IF NOT EXISTS agent_step (
    id               VARCHAR(64)  NOT NULL PRIMARY KEY,
    run_id           VARCHAR(64)  NOT NULL REFERENCES agent_run(id),
    seq              INT          NOT NULL,
    tool_name        VARCHAR(191),
    args_json        TEXT,
    idempotency_key  VARCHAR(128) NOT NULL,
    status           VARCHAR(32)  NOT NULL,
    result_summary   TEXT,
    error_message    TEXT,
    started_at       TIMESTAMP    NOT NULL,
    finished_at      TIMESTAMP,
    CONSTRAINT uq_agent_step_idem UNIQUE (idempotency_key)
);

COMMENT ON TABLE  agent_step                 IS '排查的单步';
COMMENT ON COLUMN agent_step.idempotency_key IS '幂等的物理保证；多实例下应用层幂等会失效';

CREATE INDEX IF NOT EXISTS idx_agent_step_run ON agent_step (run_id, seq);


CREATE TABLE IF NOT EXISTS tool_audit_log (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id       VARCHAR(64)  NOT NULL,
    run_id         VARCHAR(64),
    step_id        VARCHAR(64),
    tool_name      VARCHAR(191) NOT NULL,
    tool_source    VARCHAR(32)  NOT NULL,
    risk_level     VARCHAR(32)  NOT NULL,
    args_masked    TEXT         NOT NULL,
    result_masked  TEXT,
    gate_outcome   VARCHAR(32)  NOT NULL,
    denied_reason  VARCHAR(500),
    operator       VARCHAR(64),
    duration_ms    INT,
    called_at      TIMESTAMP    NOT NULL
);

COMMENT ON TABLE  tool_audit_log               IS '工具调用审计；保留期建议 180 天';
COMMENT ON COLUMN tool_audit_log.args_masked   IS '脱敏后的参数——审计表查询频率最高，不能成为敏感数据的第二个副本';
COMMENT ON COLUMN tool_audit_log.gate_outcome  IS 'PASSED / DENIED / CLAMPED / TIMED_OUT；让「哪道关卡拦下了它」可统计';
COMMENT ON COLUMN tool_audit_log.tool_source   IS 'LOCAL / MCP';

CREATE INDEX IF NOT EXISTS idx_tool_audit_trace ON tool_audit_log (trace_id, called_at);
CREATE INDEX IF NOT EXISTS idx_tool_audit_risk  ON tool_audit_log (risk_level, called_at DESC);


CREATE TABLE IF NOT EXISTS approval_record (
    id             VARCHAR(64)  NOT NULL PRIMARY KEY,
    trace_id       VARCHAR(64)  NOT NULL,
    run_id         VARCHAR(64),
    step_id        VARCHAR(64),
    tool_name      VARCHAR(191) NOT NULL,
    risk_level     VARCHAR(32)  NOT NULL,
    requester      VARCHAR(64)  NOT NULL,
    args_snapshot  TEXT         NOT NULL,
    decision       VARCHAR(32)  NOT NULL,
    approver       VARCHAR(64),
    comment        VARCHAR(500),
    requested_at   TIMESTAMP    NOT NULL,
    decided_at     TIMESTAMP,
    CONSTRAINT chk_approval_not_self CHECK (approver IS NULL OR approver <> requester)
);

COMMENT ON TABLE  approval_record               IS '审批记录；保留期永久——它是责任归属的唯一凭据';
COMMENT ON COLUMN approval_record.args_snapshot IS '审批人当时看到的内容，必须是夹紧后且脱敏后的值；否则这次审批无效';
COMMENT ON COLUMN approval_record.decision      IS 'GRANTED / REJECTED / TIMED_OUT；超时是一等公民，不是「没有记录」';

CREATE INDEX IF NOT EXISTS idx_approval_run ON approval_record (run_id);
