-- =====================================================================
-- 模型调用与成本计量（对应模块 oncall-agent）
--
-- 三个字段决定成本模型能不能落地，缺一个都不行：
--
-- 1. prompt_version —— 没有它，「改 prompt 之后质量变了」无法归因。
--    这是 AI 系统排障最基础的信息，缺了它等于没有日志。
--
-- 2. cached_tokens —— 命中缓存的输入单价是未命中的 1/30
--    （v4-pro 谷时 0.66 vs 0.022 USD/1M）。不算这一项成本模型会严重高估。
--
-- 3. is_retry / failover_from —— 重试的 token 成本只有 +1.4%（可忽略），
--    但重试的延迟是 +8s，直接击穿 P95 < 10s。
--    同一个设计决策在成本维度无所谓、在延迟维度是硬伤，所以两个维度必须分开度量。
--
-- prompt_masked 存的是脱敏后的内容：全量留痕会绕过脱敏管线。
--
-- 方言：PostgreSQL 10+
-- =====================================================================

CREATE TABLE IF NOT EXISTS llm_call_log (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    trace_id           VARCHAR(64)  NOT NULL,
    run_id             VARCHAR(64),
    call_type          VARCHAR(32)  NOT NULL,
    model              VARCHAR(64)  NOT NULL,
    prompt_version     VARCHAR(64)  NOT NULL,
    prompt_masked      TEXT,
    response_masked    TEXT,
    prompt_tokens      INT          NOT NULL,
    completion_tokens  INT          NOT NULL,
    total_tokens       INT          NOT NULL,
    cached_tokens      INT          NOT NULL DEFAULT 0,
    latency_ms         INT          NOT NULL,
    is_retry           BOOLEAN      NOT NULL DEFAULT FALSE,
    failover_from      VARCHAR(64),
    status             VARCHAR(32)  NOT NULL,
    called_at          TIMESTAMP    NOT NULL,
    PRIMARY KEY (id, called_at)
) PARTITION BY RANGE (called_at);

COMMENT ON TABLE  llm_call_log                  IS '模型调用与 token 计量；按 called_at 月分区，保留 30 天';
COMMENT ON COLUMN llm_call_log.call_type        IS 'PLANNER / EXECUTOR / REPLANNER / REPORTER / CHAT / EMBEDDING';
COMMENT ON COLUMN llm_call_log.prompt_version   IS '缺了它就无法归因「改 prompt 之后质量变了」';
COMMENT ON COLUMN llm_call_log.prompt_masked    IS '脱敏后；全量留痕会绕过脱敏管线';
COMMENT ON COLUMN llm_call_log.cached_tokens    IS '命中缓存的输入单价约为未命中的 1/30';
COMMENT ON COLUMN llm_call_log.is_retry         IS '重试的 token 成本可忽略（+1.4%），但延迟 +8s 会击穿 P95';

CREATE INDEX IF NOT EXISTS idx_llm_run   ON llm_call_log (run_id, called_at);
CREATE INDEX IF NOT EXISTS idx_llm_model ON llm_call_log (model, called_at DESC);

-- 安全网：漏建月度分区时数据落进 default，而不是插入失败丢失计量数据
CREATE TABLE IF NOT EXISTS llm_call_log_default PARTITION OF llm_call_log DEFAULT;
