package com.oncall.agent.llm;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.sql.Types;
import java.util.Objects;

/**
 * {@link LlmCallLog} 的 JDBC 实现。
 *
 * <p>只用 JDK 自带的 {@code javax.sql} / {@code java.sql}，与
 * {@code JdbcToolAuditLog} / {@code JdbcApprovalRecordStore} 一致：
 * 生产代码不引入 ORM 或连接池。
 *
 * <p><b>为什么这一张表不能像其它表那样在 Java 里放一份建表 DDL</b>：
 * {@code llm_call_log} 是 {@code PARTITION BY RANGE (called_at)} 的分区表，
 * 而各模块单测用的 H2 未必支持 PostgreSQL 的声明式分区方言。
 * 与其在 Java 里复制一份「跨方言」的 DDL——那会与 {@code db/migration/V4}
 * 分叉，而分叉的 DDL 是静默的——不如<b>只写 INSERT，建表交给 Flyway</b>，
 * 测试直接连真实 PostgreSQL。
 *
 * <p><b>INSERT 不写 {@code id}</b>：它是
 * {@code GENERATED BY DEFAULT AS IDENTITY}，由数据库分配。
 *
 * <p><b>参数化，不拼字符串</b>：{@code prompt_masked} / {@code response_masked}
 * 是模型生成的文本，拼进 SQL 就是注入面。
 */
public final class JdbcLlmCallLog implements LlmCallLog {

    /** 16 列（不含自增的 id）。列序必须与 {@link #INSERT_SQL} 的占位符一致。 */
    static final String INSERT_SQL = """
            INSERT INTO %s (
                trace_id, run_id, call_type, model, prompt_version,
                prompt_masked, response_masked,
                prompt_tokens, completion_tokens, total_tokens, cached_tokens,
                latency_ms, is_retry, failover_from, status, called_at
            ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
            """;

    private final DataSource dataSource;
    private final String table;

    public JdbcLlmCallLog(DataSource dataSource) {
        this(dataSource, "llm_call_log");
    }

    /** @param table 表名，测试里可指向临时表 */
    public JdbcLlmCallLog(DataSource dataSource, String table) {
        this.dataSource = Objects.requireNonNull(dataSource, "dataSource");
        if (table == null || table.isBlank()) {
            throw new IllegalArgumentException("table 不能为空");
        }
        this.table = table;
    }

    @Override
    public void record(LlmCallRecord r) {
        Objects.requireNonNull(r, "record");
        String sql = INSERT_SQL.formatted(table);
        try (Connection c = dataSource.getConnection();
             PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setString(1, r.traceId());
            setNullable(ps, 2, r.runId());
            ps.setString(3, r.callType());
            ps.setString(4, r.model());
            ps.setString(5, r.promptVersion());
            setNullable(ps, 6, r.promptMasked());
            setNullable(ps, 7, r.responseMasked());
            ps.setInt(8, r.promptTokens());
            ps.setInt(9, r.completionTokens());
            ps.setInt(10, r.totalTokens());
            ps.setInt(11, r.cachedTokens());
            // latency_ms 是 INT；CallOutcome 给的是 long。
            // 超界说明计时器坏了，截断成 Integer.MAX_VALUE 会留下一个看起来合理的假值。
            if (r.latencyMs() > Integer.MAX_VALUE) {
                throw new IllegalStateException(
                        "latencyMs 超出 INT 范围，拒绝写入而不是截断: " + r.latencyMs());
            }
            ps.setInt(12, (int) r.latencyMs());
            ps.setBoolean(13, r.retry());
            setNullable(ps, 14, r.failoverFrom());
            ps.setString(15, r.status());
            ps.setTimestamp(16, Timestamp.from(r.calledAt()));
            ps.executeUpdate();
        } catch (SQLException e) {
            // 不吞：计量丢失是静默的，成本报表只会偏小而没人怀疑。
            throw new IllegalStateException("写入 " + table + " 失败: " + e.getMessage(), e);
        }
    }

    private static void setNullable(PreparedStatement ps, int i, String v)
            throws SQLException {
        if (v == null) {
            ps.setNull(i, Types.VARCHAR);
        } else {
            ps.setString(i, v);
        }
    }
}
