package com.oncall.config.store;

import com.oncall.config.ConfigAuditLog;
import com.oncall.config.ConfigChange;
import com.oncall.config.ConfigTier;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

/**
 * 配置变更审计的 JDBC 实现。
 *
 * <p>配置可以在运行期改，就意味着"系统为什么突然表现不一样"必须可追溯。
 * 这张表的保留期应与 {@code tool_audit_log} 同级（建议 180 天）——
 * 一次误配置的影响可能几周后才被发现。
 */
public final class JdbcConfigAuditLog implements ConfigAuditLog {

    public static final String CREATE_TABLE_SQL = """
            CREATE TABLE IF NOT EXISTS %s (
                id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                config_key   VARCHAR(191)  NOT NULL,
                old_value    VARCHAR(2000),
                new_value    VARCHAR(2000),
                operator     VARCHAR(64)   NOT NULL,
                reason       VARCHAR(500),
                tier         VARCHAR(32)   NOT NULL,
                changed_at   TIMESTAMP     NOT NULL
            )
            """;

    private final DataSource dataSource;
    private final String table;

    public JdbcConfigAuditLog(DataSource dataSource) {
        this(dataSource, "config_audit_log");
    }

    public JdbcConfigAuditLog(DataSource dataSource, String table) {
        if (dataSource == null) {
            throw new IllegalArgumentException("dataSource 不能为 null");
        }
        this.dataSource = dataSource;
        this.table = table;
    }

    public void createSchemaIfMissing() {
        try (Connection c = dataSource.getConnection(); Statement st = c.createStatement()) {
            st.execute(String.format(CREATE_TABLE_SQL, table));
        } catch (SQLException e) {
            throw new IllegalStateException("建表失败：" + table, e);
        }
    }

    @Override
    public void record(ConfigChange change) {
        if (change == null) {
            throw new IllegalArgumentException("change 不能为 null");
        }
        String sql = "INSERT INTO " + table
                + " (config_key, old_value, new_value, operator, reason, tier, changed_at)"
                + " VALUES (?, ?, ?, ?, ?, ?, ?)";
        try (Connection c = dataSource.getConnection(); PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setString(1, change.key());
            ps.setString(2, change.oldValue());
            ps.setString(3, change.newValue());
            ps.setString(4, change.operator());
            ps.setString(5, change.reason());
            ps.setString(6, change.tier() == null ? ConfigTier.RUNTIME_HOT.name() : change.tier().name());
            ps.setTimestamp(7, Timestamp.from(Instant.ofEpochMilli(change.timestampMillis())));
            ps.executeUpdate();
        } catch (SQLException e) {
            // 审计写失败必须让调用方知道：一条没落库的配置变更等于没有审计
            throw new IllegalStateException("写入配置审计失败：" + change.key(), e);
        }
    }

    @Override
    public List<ConfigChange> history(String key) {
        String sql = "SELECT config_key, old_value, new_value, operator, reason, tier, changed_at FROM "
                + table + " WHERE config_key = ? ORDER BY changed_at ASC, id ASC";
        return query(sql, ps -> ps.setString(1, key));
    }

    @Override
    public List<ConfigChange> recent(int limit) {
        if (limit <= 0) {
            return List.of();
        }
        String sql = "SELECT config_key, old_value, new_value, operator, reason, tier, changed_at FROM "
                + table + " ORDER BY changed_at DESC, id DESC LIMIT ?";
        return query(sql, ps -> ps.setInt(1, limit));
    }

    private List<ConfigChange> query(String sql, Binder binder) {
        List<ConfigChange> out = new ArrayList<>();
        try (Connection c = dataSource.getConnection(); PreparedStatement ps = c.prepareStatement(sql)) {
            binder.bind(ps);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    Timestamp at = rs.getTimestamp("changed_at");
                    out.add(new ConfigChange(
                            rs.getString("config_key"),
                            rs.getString("old_value"),
                            rs.getString("new_value"),
                            rs.getString("operator"),
                            rs.getString("reason"),
                            ConfigTier.valueOf(rs.getString("tier")),
                            at == null ? 0L : at.getTime()));
                }
            }
        } catch (SQLException e) {
            throw new IllegalStateException("查询配置审计失败", e);
        }
        return out;
    }

    @FunctionalInterface
    private interface Binder {
        void bind(PreparedStatement ps) throws SQLException;
    }
}
